# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniil/tetris-rtos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniil/tetris-rtos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniil/tetris-rtos/CMakeFiles /home/daniil/tetris-rtos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniil/tetris-rtos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named firmware

# Build rule for target.
firmware: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 firmware
.PHONY : firmware

# fast build rule for target.
firmware/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/build
.PHONY : firmware/fast

#=============================================================================
# Target rules for targets named freertos_kernel

# Build rule for target.
freertos_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freertos_kernel
.PHONY : freertos_kernel

# fast build rule for target.
freertos_kernel/fast:
	$(MAKE) $(MAKESILENT) -f FreeRTOS/Source/CMakeFiles/freertos_kernel.dir/build.make FreeRTOS/Source/CMakeFiles/freertos_kernel.dir/build
.PHONY : freertos_kernel/fast

#=============================================================================
# Target rules for targets named freertos_kernel_port

# Build rule for target.
freertos_kernel_port: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freertos_kernel_port
.PHONY : freertos_kernel_port

# fast build rule for target.
freertos_kernel_port/fast:
	$(MAKE) $(MAKESILENT) -f FreeRTOS/Source/portable/CMakeFiles/freertos_kernel_port.dir/build.make FreeRTOS/Source/portable/CMakeFiles/freertos_kernel_port.dir/build
.PHONY : freertos_kernel_port/fast

core/src/stm32f10x_can.obj: core/src/stm32f10x_can.c.obj
.PHONY : core/src/stm32f10x_can.obj

# target to build an object file
core/src/stm32f10x_can.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_can.c.obj
.PHONY : core/src/stm32f10x_can.c.obj

core/src/stm32f10x_can.i: core/src/stm32f10x_can.c.i
.PHONY : core/src/stm32f10x_can.i

# target to preprocess a source file
core/src/stm32f10x_can.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_can.c.i
.PHONY : core/src/stm32f10x_can.c.i

core/src/stm32f10x_can.s: core/src/stm32f10x_can.c.s
.PHONY : core/src/stm32f10x_can.s

# target to generate assembly for a file
core/src/stm32f10x_can.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_can.c.s
.PHONY : core/src/stm32f10x_can.c.s

core/src/stm32f10x_gpio.obj: core/src/stm32f10x_gpio.c.obj
.PHONY : core/src/stm32f10x_gpio.obj

# target to build an object file
core/src/stm32f10x_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_gpio.c.obj
.PHONY : core/src/stm32f10x_gpio.c.obj

core/src/stm32f10x_gpio.i: core/src/stm32f10x_gpio.c.i
.PHONY : core/src/stm32f10x_gpio.i

# target to preprocess a source file
core/src/stm32f10x_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_gpio.c.i
.PHONY : core/src/stm32f10x_gpio.c.i

core/src/stm32f10x_gpio.s: core/src/stm32f10x_gpio.c.s
.PHONY : core/src/stm32f10x_gpio.s

# target to generate assembly for a file
core/src/stm32f10x_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_gpio.c.s
.PHONY : core/src/stm32f10x_gpio.c.s

core/src/stm32f10x_i2c.obj: core/src/stm32f10x_i2c.c.obj
.PHONY : core/src/stm32f10x_i2c.obj

# target to build an object file
core/src/stm32f10x_i2c.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_i2c.c.obj
.PHONY : core/src/stm32f10x_i2c.c.obj

core/src/stm32f10x_i2c.i: core/src/stm32f10x_i2c.c.i
.PHONY : core/src/stm32f10x_i2c.i

# target to preprocess a source file
core/src/stm32f10x_i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_i2c.c.i
.PHONY : core/src/stm32f10x_i2c.c.i

core/src/stm32f10x_i2c.s: core/src/stm32f10x_i2c.c.s
.PHONY : core/src/stm32f10x_i2c.s

# target to generate assembly for a file
core/src/stm32f10x_i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_i2c.c.s
.PHONY : core/src/stm32f10x_i2c.c.s

core/src/stm32f10x_lib.obj: core/src/stm32f10x_lib.c.obj
.PHONY : core/src/stm32f10x_lib.obj

# target to build an object file
core/src/stm32f10x_lib.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_lib.c.obj
.PHONY : core/src/stm32f10x_lib.c.obj

core/src/stm32f10x_lib.i: core/src/stm32f10x_lib.c.i
.PHONY : core/src/stm32f10x_lib.i

# target to preprocess a source file
core/src/stm32f10x_lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_lib.c.i
.PHONY : core/src/stm32f10x_lib.c.i

core/src/stm32f10x_lib.s: core/src/stm32f10x_lib.c.s
.PHONY : core/src/stm32f10x_lib.s

# target to generate assembly for a file
core/src/stm32f10x_lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_lib.c.s
.PHONY : core/src/stm32f10x_lib.c.s

core/src/stm32f10x_nvic.obj: core/src/stm32f10x_nvic.c.obj
.PHONY : core/src/stm32f10x_nvic.obj

# target to build an object file
core/src/stm32f10x_nvic.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_nvic.c.obj
.PHONY : core/src/stm32f10x_nvic.c.obj

core/src/stm32f10x_nvic.i: core/src/stm32f10x_nvic.c.i
.PHONY : core/src/stm32f10x_nvic.i

# target to preprocess a source file
core/src/stm32f10x_nvic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_nvic.c.i
.PHONY : core/src/stm32f10x_nvic.c.i

core/src/stm32f10x_nvic.s: core/src/stm32f10x_nvic.c.s
.PHONY : core/src/stm32f10x_nvic.s

# target to generate assembly for a file
core/src/stm32f10x_nvic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_nvic.c.s
.PHONY : core/src/stm32f10x_nvic.c.s

core/src/stm32f10x_rcc.obj: core/src/stm32f10x_rcc.c.obj
.PHONY : core/src/stm32f10x_rcc.obj

# target to build an object file
core/src/stm32f10x_rcc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_rcc.c.obj
.PHONY : core/src/stm32f10x_rcc.c.obj

core/src/stm32f10x_rcc.i: core/src/stm32f10x_rcc.c.i
.PHONY : core/src/stm32f10x_rcc.i

# target to preprocess a source file
core/src/stm32f10x_rcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_rcc.c.i
.PHONY : core/src/stm32f10x_rcc.c.i

core/src/stm32f10x_rcc.s: core/src/stm32f10x_rcc.c.s
.PHONY : core/src/stm32f10x_rcc.s

# target to generate assembly for a file
core/src/stm32f10x_rcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_rcc.c.s
.PHONY : core/src/stm32f10x_rcc.c.s

core/src/stm32f10x_spi.obj: core/src/stm32f10x_spi.c.obj
.PHONY : core/src/stm32f10x_spi.obj

# target to build an object file
core/src/stm32f10x_spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_spi.c.obj
.PHONY : core/src/stm32f10x_spi.c.obj

core/src/stm32f10x_spi.i: core/src/stm32f10x_spi.c.i
.PHONY : core/src/stm32f10x_spi.i

# target to preprocess a source file
core/src/stm32f10x_spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_spi.c.i
.PHONY : core/src/stm32f10x_spi.c.i

core/src/stm32f10x_spi.s: core/src/stm32f10x_spi.c.s
.PHONY : core/src/stm32f10x_spi.s

# target to generate assembly for a file
core/src/stm32f10x_spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_spi.c.s
.PHONY : core/src/stm32f10x_spi.c.s

core/src/stm32f10x_systick.obj: core/src/stm32f10x_systick.c.obj
.PHONY : core/src/stm32f10x_systick.obj

# target to build an object file
core/src/stm32f10x_systick.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_systick.c.obj
.PHONY : core/src/stm32f10x_systick.c.obj

core/src/stm32f10x_systick.i: core/src/stm32f10x_systick.c.i
.PHONY : core/src/stm32f10x_systick.i

# target to preprocess a source file
core/src/stm32f10x_systick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_systick.c.i
.PHONY : core/src/stm32f10x_systick.c.i

core/src/stm32f10x_systick.s: core/src/stm32f10x_systick.c.s
.PHONY : core/src/stm32f10x_systick.s

# target to generate assembly for a file
core/src/stm32f10x_systick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_systick.c.s
.PHONY : core/src/stm32f10x_systick.c.s

core/src/stm32f10x_usart.obj: core/src/stm32f10x_usart.c.obj
.PHONY : core/src/stm32f10x_usart.obj

# target to build an object file
core/src/stm32f10x_usart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_usart.c.obj
.PHONY : core/src/stm32f10x_usart.c.obj

core/src/stm32f10x_usart.i: core/src/stm32f10x_usart.c.i
.PHONY : core/src/stm32f10x_usart.i

# target to preprocess a source file
core/src/stm32f10x_usart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_usart.c.i
.PHONY : core/src/stm32f10x_usart.c.i

core/src/stm32f10x_usart.s: core/src/stm32f10x_usart.c.s
.PHONY : core/src/stm32f10x_usart.s

# target to generate assembly for a file
core/src/stm32f10x_usart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/stm32f10x_usart.c.s
.PHONY : core/src/stm32f10x_usart.c.s

core/src/syscalls.obj: core/src/syscalls.c.obj
.PHONY : core/src/syscalls.obj

# target to build an object file
core/src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/syscalls.c.obj
.PHONY : core/src/syscalls.c.obj

core/src/syscalls.i: core/src/syscalls.c.i
.PHONY : core/src/syscalls.i

# target to preprocess a source file
core/src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/syscalls.c.i
.PHONY : core/src/syscalls.c.i

core/src/syscalls.s: core/src/syscalls.c.s
.PHONY : core/src/syscalls.s

# target to generate assembly for a file
core/src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/syscalls.c.s
.PHONY : core/src/syscalls.c.s

core/src/system_stm32f1xx.obj: core/src/system_stm32f1xx.c.obj
.PHONY : core/src/system_stm32f1xx.obj

# target to build an object file
core/src/system_stm32f1xx.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/system_stm32f1xx.c.obj
.PHONY : core/src/system_stm32f1xx.c.obj

core/src/system_stm32f1xx.i: core/src/system_stm32f1xx.c.i
.PHONY : core/src/system_stm32f1xx.i

# target to preprocess a source file
core/src/system_stm32f1xx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/system_stm32f1xx.c.i
.PHONY : core/src/system_stm32f1xx.c.i

core/src/system_stm32f1xx.s: core/src/system_stm32f1xx.c.s
.PHONY : core/src/system_stm32f1xx.s

# target to generate assembly for a file
core/src/system_stm32f1xx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/src/system_stm32f1xx.c.s
.PHONY : core/src/system_stm32f1xx.c.s

core/startup_stm32f103xb.obj: core/startup_stm32f103xb.S.obj
.PHONY : core/startup_stm32f103xb.obj

# target to build an object file
core/startup_stm32f103xb.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/core/startup_stm32f103xb.S.obj
.PHONY : core/startup_stm32f103xb.S.obj

lib/tetris/TETRIS_GAME_STATE.obj: lib/tetris/TETRIS_GAME_STATE.cpp.obj
.PHONY : lib/tetris/TETRIS_GAME_STATE.obj

# target to build an object file
lib/tetris/TETRIS_GAME_STATE.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/TETRIS_GAME_STATE.cpp.obj
.PHONY : lib/tetris/TETRIS_GAME_STATE.cpp.obj

lib/tetris/TETRIS_GAME_STATE.i: lib/tetris/TETRIS_GAME_STATE.cpp.i
.PHONY : lib/tetris/TETRIS_GAME_STATE.i

# target to preprocess a source file
lib/tetris/TETRIS_GAME_STATE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/TETRIS_GAME_STATE.cpp.i
.PHONY : lib/tetris/TETRIS_GAME_STATE.cpp.i

lib/tetris/TETRIS_GAME_STATE.s: lib/tetris/TETRIS_GAME_STATE.cpp.s
.PHONY : lib/tetris/TETRIS_GAME_STATE.s

# target to generate assembly for a file
lib/tetris/TETRIS_GAME_STATE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/TETRIS_GAME_STATE.cpp.s
.PHONY : lib/tetris/TETRIS_GAME_STATE.cpp.s

lib/tetris/TETROMINOS.obj: lib/tetris/TETROMINOS.cpp.obj
.PHONY : lib/tetris/TETROMINOS.obj

# target to build an object file
lib/tetris/TETROMINOS.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/TETROMINOS.cpp.obj
.PHONY : lib/tetris/TETROMINOS.cpp.obj

lib/tetris/TETROMINOS.i: lib/tetris/TETROMINOS.cpp.i
.PHONY : lib/tetris/TETROMINOS.i

# target to preprocess a source file
lib/tetris/TETROMINOS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/TETROMINOS.cpp.i
.PHONY : lib/tetris/TETROMINOS.cpp.i

lib/tetris/TETROMINOS.s: lib/tetris/TETROMINOS.cpp.s
.PHONY : lib/tetris/TETROMINOS.s

# target to generate assembly for a file
lib/tetris/TETROMINOS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/TETROMINOS.cpp.s
.PHONY : lib/tetris/TETROMINOS.cpp.s

lib/tetris/board.obj: lib/tetris/board.cpp.obj
.PHONY : lib/tetris/board.obj

# target to build an object file
lib/tetris/board.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/board.cpp.obj
.PHONY : lib/tetris/board.cpp.obj

lib/tetris/board.i: lib/tetris/board.cpp.i
.PHONY : lib/tetris/board.i

# target to preprocess a source file
lib/tetris/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/board.cpp.i
.PHONY : lib/tetris/board.cpp.i

lib/tetris/board.s: lib/tetris/board.cpp.s
.PHONY : lib/tetris/board.s

# target to generate assembly for a file
lib/tetris/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/board.cpp.s
.PHONY : lib/tetris/board.cpp.s

lib/tetris/holdPiece.obj: lib/tetris/holdPiece.cpp.obj
.PHONY : lib/tetris/holdPiece.obj

# target to build an object file
lib/tetris/holdPiece.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/holdPiece.cpp.obj
.PHONY : lib/tetris/holdPiece.cpp.obj

lib/tetris/holdPiece.i: lib/tetris/holdPiece.cpp.i
.PHONY : lib/tetris/holdPiece.i

# target to preprocess a source file
lib/tetris/holdPiece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/holdPiece.cpp.i
.PHONY : lib/tetris/holdPiece.cpp.i

lib/tetris/holdPiece.s: lib/tetris/holdPiece.cpp.s
.PHONY : lib/tetris/holdPiece.s

# target to generate assembly for a file
lib/tetris/holdPiece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/holdPiece.cpp.s
.PHONY : lib/tetris/holdPiece.cpp.s

lib/tetris/piece.obj: lib/tetris/piece.cpp.obj
.PHONY : lib/tetris/piece.obj

# target to build an object file
lib/tetris/piece.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/piece.cpp.obj
.PHONY : lib/tetris/piece.cpp.obj

lib/tetris/piece.i: lib/tetris/piece.cpp.i
.PHONY : lib/tetris/piece.i

# target to preprocess a source file
lib/tetris/piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/piece.cpp.i
.PHONY : lib/tetris/piece.cpp.i

lib/tetris/piece.s: lib/tetris/piece.cpp.s
.PHONY : lib/tetris/piece.s

# target to generate assembly for a file
lib/tetris/piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/piece.cpp.s
.PHONY : lib/tetris/piece.cpp.s

lib/tetris/srs.obj: lib/tetris/srs.cpp.obj
.PHONY : lib/tetris/srs.obj

# target to build an object file
lib/tetris/srs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/srs.cpp.obj
.PHONY : lib/tetris/srs.cpp.obj

lib/tetris/srs.i: lib/tetris/srs.cpp.i
.PHONY : lib/tetris/srs.i

# target to preprocess a source file
lib/tetris/srs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/srs.cpp.i
.PHONY : lib/tetris/srs.cpp.i

lib/tetris/srs.s: lib/tetris/srs.cpp.s
.PHONY : lib/tetris/srs.s

# target to generate assembly for a file
lib/tetris/srs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/srs.cpp.s
.PHONY : lib/tetris/srs.cpp.s

lib/tetris/tetris_queue.obj: lib/tetris/tetris_queue.cpp.obj
.PHONY : lib/tetris/tetris_queue.obj

# target to build an object file
lib/tetris/tetris_queue.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/tetris_queue.cpp.obj
.PHONY : lib/tetris/tetris_queue.cpp.obj

lib/tetris/tetris_queue.i: lib/tetris/tetris_queue.cpp.i
.PHONY : lib/tetris/tetris_queue.i

# target to preprocess a source file
lib/tetris/tetris_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/tetris_queue.cpp.i
.PHONY : lib/tetris/tetris_queue.cpp.i

lib/tetris/tetris_queue.s: lib/tetris/tetris_queue.cpp.s
.PHONY : lib/tetris/tetris_queue.s

# target to generate assembly for a file
lib/tetris/tetris_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/tetris/tetris_queue.cpp.s
.PHONY : lib/tetris/tetris_queue.cpp.s

lib/usart/usart_STM32.obj: lib/usart/usart_STM32.cpp.obj
.PHONY : lib/usart/usart_STM32.obj

# target to build an object file
lib/usart/usart_STM32.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/usart/usart_STM32.cpp.obj
.PHONY : lib/usart/usart_STM32.cpp.obj

lib/usart/usart_STM32.i: lib/usart/usart_STM32.cpp.i
.PHONY : lib/usart/usart_STM32.i

# target to preprocess a source file
lib/usart/usart_STM32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/usart/usart_STM32.cpp.i
.PHONY : lib/usart/usart_STM32.cpp.i

lib/usart/usart_STM32.s: lib/usart/usart_STM32.cpp.s
.PHONY : lib/usart/usart_STM32.s

# target to generate assembly for a file
lib/usart/usart_STM32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/usart/usart_STM32.cpp.s
.PHONY : lib/usart/usart_STM32.cpp.s

lib/utils/util_STM32.obj: lib/utils/util_STM32.cpp.obj
.PHONY : lib/utils/util_STM32.obj

# target to build an object file
lib/utils/util_STM32.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/utils/util_STM32.cpp.obj
.PHONY : lib/utils/util_STM32.cpp.obj

lib/utils/util_STM32.i: lib/utils/util_STM32.cpp.i
.PHONY : lib/utils/util_STM32.i

# target to preprocess a source file
lib/utils/util_STM32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/utils/util_STM32.cpp.i
.PHONY : lib/utils/util_STM32.cpp.i

lib/utils/util_STM32.s: lib/utils/util_STM32.cpp.s
.PHONY : lib/utils/util_STM32.s

# target to generate assembly for a file
lib/utils/util_STM32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/lib/utils/util_STM32.cpp.s
.PHONY : lib/utils/util_STM32.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmware.dir/build.make CMakeFiles/firmware.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... firmware"
	@echo "... freertos_kernel"
	@echo "... freertos_kernel_port"
	@echo "... core/src/stm32f10x_can.obj"
	@echo "... core/src/stm32f10x_can.i"
	@echo "... core/src/stm32f10x_can.s"
	@echo "... core/src/stm32f10x_gpio.obj"
	@echo "... core/src/stm32f10x_gpio.i"
	@echo "... core/src/stm32f10x_gpio.s"
	@echo "... core/src/stm32f10x_i2c.obj"
	@echo "... core/src/stm32f10x_i2c.i"
	@echo "... core/src/stm32f10x_i2c.s"
	@echo "... core/src/stm32f10x_lib.obj"
	@echo "... core/src/stm32f10x_lib.i"
	@echo "... core/src/stm32f10x_lib.s"
	@echo "... core/src/stm32f10x_nvic.obj"
	@echo "... core/src/stm32f10x_nvic.i"
	@echo "... core/src/stm32f10x_nvic.s"
	@echo "... core/src/stm32f10x_rcc.obj"
	@echo "... core/src/stm32f10x_rcc.i"
	@echo "... core/src/stm32f10x_rcc.s"
	@echo "... core/src/stm32f10x_spi.obj"
	@echo "... core/src/stm32f10x_spi.i"
	@echo "... core/src/stm32f10x_spi.s"
	@echo "... core/src/stm32f10x_systick.obj"
	@echo "... core/src/stm32f10x_systick.i"
	@echo "... core/src/stm32f10x_systick.s"
	@echo "... core/src/stm32f10x_usart.obj"
	@echo "... core/src/stm32f10x_usart.i"
	@echo "... core/src/stm32f10x_usart.s"
	@echo "... core/src/syscalls.obj"
	@echo "... core/src/syscalls.i"
	@echo "... core/src/syscalls.s"
	@echo "... core/src/system_stm32f1xx.obj"
	@echo "... core/src/system_stm32f1xx.i"
	@echo "... core/src/system_stm32f1xx.s"
	@echo "... core/startup_stm32f103xb.obj"
	@echo "... lib/tetris/TETRIS_GAME_STATE.obj"
	@echo "... lib/tetris/TETRIS_GAME_STATE.i"
	@echo "... lib/tetris/TETRIS_GAME_STATE.s"
	@echo "... lib/tetris/TETROMINOS.obj"
	@echo "... lib/tetris/TETROMINOS.i"
	@echo "... lib/tetris/TETROMINOS.s"
	@echo "... lib/tetris/board.obj"
	@echo "... lib/tetris/board.i"
	@echo "... lib/tetris/board.s"
	@echo "... lib/tetris/holdPiece.obj"
	@echo "... lib/tetris/holdPiece.i"
	@echo "... lib/tetris/holdPiece.s"
	@echo "... lib/tetris/piece.obj"
	@echo "... lib/tetris/piece.i"
	@echo "... lib/tetris/piece.s"
	@echo "... lib/tetris/srs.obj"
	@echo "... lib/tetris/srs.i"
	@echo "... lib/tetris/srs.s"
	@echo "... lib/tetris/tetris_queue.obj"
	@echo "... lib/tetris/tetris_queue.i"
	@echo "... lib/tetris/tetris_queue.s"
	@echo "... lib/usart/usart_STM32.obj"
	@echo "... lib/usart/usart_STM32.i"
	@echo "... lib/usart/usart_STM32.s"
	@echo "... lib/utils/util_STM32.obj"
	@echo "... lib/utils/util_STM32.i"
	@echo "... lib/utils/util_STM32.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

