#include "TETRIS_ENUMS.h"

#ifndef BOARD_STATE_H
#define BOARD_STATE_H

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 23

const PieceType DEFAULT_BOARD_STATE[BOARD_HEIGHT][BOARD_WIDTH] = {
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N},
    {PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N, PIECE_TYPE_N}
};

#endif